# Top-level build orchestration for the BioSig SoC project.
# Note: targets use POSIX tools (python, rm). On Windows use the PowerShell
# equivalents shown in README.md, or run under Git Bash / WSL / make.

.PHONY: all sim firmware web test docs clean

all: sim test

sim:
	python hardware/spice/full_chain_sim.py
	python hardware/spice/ina_simulation.py
	python hardware/spice/filter_simulation.py
	python dsp/filter_design.py
	python dsp/verify_filters.py
	python dsp/noise_budget.py

firmware:
	cd firmware && $(MAKE) all

web:
	cd web && python app.py

test:
	python -m pytest tests/ -v

docs:
	python dsp/characterization.py

clean:
	cd firmware && $(MAKE) clean
	rm -rf web/__pycache__ dsp/__pycache__ tests/__pycache__ wireless/__pycache__
	rm -f firmware/Core/Inc/filters.h   # regenerated by sim
