"""
filter_design.py - Design all filters and export Q15 coefficients for STM32.

Designs:
  1. 60 Hz notch filter (IIR biquad, 2nd order)
  2. 50 Hz notch filter (IIR biquad, 2nd order)
  3. Bandpass FIR 0.5-40 Hz (128-tap, firwin2 / Hamming window)
  4. Highpass reference 0.05 Hz (for SPICE / simulation reference)

Exports:
  - firmware/Core/Inc/filters.h : C header with Q15 coefficient arrays
  - dsp/filter_plots/           : PNG frequency-response plots for each filter
  - dsp/filter_specs.json       : design parameters for documentation

Q15 NOTES:
  - Q15 coefficients: multiply float by 32768, round to int16, clamp +/-32767.
  - IIR biquad CMSIS format: [b0, b1, b2, -a1, -a2] (CMSIS negates feedback).
  - IIR postshift: notch numerator/denominator coeffs can exceed 1.0, so we
    pre-scale by 1/2 (postshift = 1) to keep everything inside Q15 range.
  - FIR: linear-phase, symmetric. Group delay = (N-1)/(2*fs).
"""

from __future__ import annotations

import json
import os

import numpy as np
import scipy.signal as sig

# matplotlib is optional at runtime (plots are a nice-to-have, not required
# for header generation). Guard the import so the script still emits filters.h
# on a headless box without matplotlib installed.
try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    _HAVE_MPL = True
except Exception:  # pragma: no cover - environment dependent
    _HAVE_MPL = False

FS = 500.0  # Sampling frequency (Hz)
FIR_NUM_TAPS = 128
NOTCH_R = 0.985  # pole radius -> notch bandwidth ~ (1-r)/pi * fs
IIR_POSTSHIFT = 1  # coefficients pre-scaled by 2^-postshift

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HEADER_PATH = os.path.join(ROOT, "firmware", "Core", "Inc", "filters.h")
PLOT_DIR = os.path.join(HERE, "filter_plots")
SPECS_PATH = os.path.join(HERE, "filter_specs.json")


def design_notch(f0: float, fs: float, r: float = NOTCH_R):
    """Design a 2nd-order IIR notch filter.

    H(z) = (1 - 2cos(w0) z^-1 + z^-2) / (1 - 2 r cos(w0) z^-1 + r^2 z^-2)
    """
    w0 = 2 * np.pi * f0 / fs
    b = np.array([1.0, -2.0 * np.cos(w0), 1.0])
    a = np.array([1.0, -2.0 * r * np.cos(w0), r * r])
    # Normalize numerator for ~0 dB passband gain at DC/Nyquist.
    gain = np.sum(a) / np.sum(b)
    b = b * gain
    return b, a


def design_bandpass_fir(flow: float, fhigh: float, fs: float, numtaps: int = FIR_NUM_TAPS):
    """Design a bandpass FIR via firwin2 (window method, Hamming)."""
    nyq = fs / 2.0
    freq = [0.0, flow * 0.5, flow, fhigh, fhigh * 1.5, nyq]
    gain = [0.0, 0.0, 1.0, 1.0, 0.0, 0.0]
    freq_norm = [f / nyq for f in freq]
    # firwin2 requires the first freq == 0 and last == 1.0
    freq_norm[0] = 0.0
    freq_norm[-1] = 1.0
    h = sig.firwin2(numtaps, freq_norm, gain, window="hamming")
    return h


def float_to_q15(coeffs: np.ndarray) -> np.ndarray:
    """Convert float coefficients to a Q15 int16 array (clamped)."""
    scaled = np.clip(coeffs, -1.0, 1.0 - 1.0 / 32768.0) * 32768.0
    return np.round(scaled).astype(np.int16)


def _biquad_to_cmsis_q15(b: np.ndarray, a: np.ndarray, postshift: int) -> list[int]:
    """Return CMSIS DF1 Q15 layout [b0, b1, b2, -a1, -a2] for one stage.

    Pre-scale all coefficients by 2^-postshift so they fit in Q15, then the
    runtime applies a left shift of `postshift` to restore the gain.
    """
    scale = 1.0 / (2 ** postshift)
    coeffs = np.array([b[0], b[1], b[2], -a[1], -a[2]]) * scale
    return float_to_q15(coeffs).tolist()


def _fmt_row(values, per_line=8, indent="    "):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(f"{v:6d}" for v in values[i : i + per_line])
        lines.append(indent + chunk + ",")
    return "\n".join(lines)


def export_c_header(notch60, notch50, fir_bp_q15, specs):
    b60, a60 = notch60
    b50, a50 = notch50

    s60 = _biquad_to_cmsis_q15(b60, a60, IIR_POSTSHIFT)
    s50 = _biquad_to_cmsis_q15(b50, a50, IIR_POSTSHIFT)

    # Two identical cascaded stages per notch sharpen the null.
    notch60_coeffs = s60 + s60
    notch50_coeffs = s50 + s50

    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w", encoding="utf-8") as f:
        f.write(
            "/*\n"
            " * filters.h - Q15 filter coefficients for STM32 CMSIS-DSP.\n"
            " * Generated by dsp/filter_design.py -- DO NOT EDIT MANUALLY.\n"
            " *\n"
            f" * fs = {FS:.1f} Hz, FIR taps = {FIR_NUM_TAPS}, IIR postshift = {IIR_POSTSHIFT}\n"
            f" * 60 Hz notch attenuation : {specs['notch60_atten_db']:.1f} dB\n"
            f" * 50 Hz notch attenuation : {specs['notch50_atten_db']:.1f} dB\n"
            f" * FIR group delay         : {specs['fir_group_delay_ms']:.1f} ms\n"
            " */\n\n"
            "#ifndef FILTERS_H\n#define FILTERS_H\n\n"
            "#include \"arm_math.h\"\n\n"
            "#define FILTER_FS_HZ          500\n"
            f"#define FIR_NUM_TAPS          {FIR_NUM_TAPS}\n"
            "#define IIR_NUM_STAGES        2\n"
            f"#define IIR_POST_SHIFT        {IIR_POSTSHIFT}\n\n"
        )

        f.write("/* 60 Hz notch -- CMSIS DF1 Q15 [b0, b1, b2, -a1, -a2] x stages */\n")
        f.write("static const q15_t notch_60hz_coeffs_q15[] = {\n")
        f.write(_fmt_row(notch60_coeffs, per_line=5))
        f.write("\n};\n\n")

        f.write("/* 50 Hz notch -- CMSIS DF1 Q15 [b0, b1, b2, -a1, -a2] x stages */\n")
        f.write("static const q15_t notch_50hz_coeffs_q15[] = {\n")
        f.write(_fmt_row(notch50_coeffs, per_line=5))
        f.write("\n};\n\n")

        f.write("/* Bandpass FIR 0.5-40 Hz, 128-tap, symmetric, Q15 */\n")
        f.write(f"static const q15_t fir_bp_coeffs_q15[{FIR_NUM_TAPS}] = {{\n")
        f.write(_fmt_row(fir_bp_q15.tolist(), per_line=8))
        f.write("\n};\n\n")

        f.write("#endif /* FILTERS_H */\n")


def _atten_db_at(b, a, f0, fs):
    w, h = sig.freqz(b, a, worN=[2 * np.pi * f0 / fs])
    return -20.0 * np.log10(np.abs(h[0]) + 1e-12)


def plot_frequency_responses(notch60, notch50, fir_bp):
    if not _HAVE_MPL:
        print("matplotlib not available - skipping plots")
        return
    os.makedirs(PLOT_DIR, exist_ok=True)

    # Notch responses
    for name, (b, a) in {"notch_60hz": notch60, "notch_50hz": notch50}.items():
        w, h = sig.freqz(b, a, worN=4096, fs=FS)
        plt.figure(figsize=(8, 4))
        plt.plot(w, 20 * np.log10(np.abs(h) + 1e-12), color="#f59e0b")
        plt.title(f"{name} frequency response")
        plt.xlabel("Frequency (Hz)")
        plt.ylabel("Magnitude (dB)")
        plt.grid(True, alpha=0.3)
        plt.ylim(-60, 5)
        plt.tight_layout()
        plt.savefig(os.path.join(PLOT_DIR, f"{name}.png"), dpi=110)
        plt.close()

    # FIR bandpass
    w, h = sig.freqz(fir_bp, worN=4096, fs=FS)
    plt.figure(figsize=(8, 4))
    plt.plot(w, 20 * np.log10(np.abs(h) + 1e-12), color="#22d3ee")
    plt.title("Bandpass FIR 0.5-40 Hz frequency response")
    plt.xlabel("Frequency (Hz)")
    plt.ylabel("Magnitude (dB)")
    plt.grid(True, alpha=0.3)
    plt.ylim(-100, 5)
    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "fir_bandpass.png"), dpi=110)
    plt.close()
    print(f"Plots saved to {PLOT_DIR}")


def main():
    notch60 = design_notch(60.0, FS)
    notch50 = design_notch(50.0, FS)
    fir_bp = design_bandpass_fir(0.5, 40.0, FS, numtaps=FIR_NUM_TAPS)
    fir_bp_q15 = float_to_q15(fir_bp)

    # Verify FIR symmetry after quantization.
    symmetric = bool(np.array_equal(fir_bp_q15, fir_bp_q15[::-1]))

    specs = {
        "fs_hz": FS,
        "fir_num_taps": FIR_NUM_TAPS,
        "fir_group_delay_ms": (FIR_NUM_TAPS - 1) / (2 * FS) * 1000.0,
        "fir_symmetric": symmetric,
        "fir_max_q15": int(np.max(np.abs(fir_bp_q15))),
        "notch_r": NOTCH_R,
        "notch60_atten_db": float(_atten_db_at(*notch60, 60.0, FS)),
        "notch50_atten_db": float(_atten_db_at(*notch50, 50.0, FS)),
        "iir_postshift": IIR_POSTSHIFT,
    }

    export_c_header(notch60, notch50, fir_bp_q15, specs)
    plot_frequency_responses(notch60, notch50, fir_bp)

    with open(SPECS_PATH, "w", encoding="utf-8") as f:
        json.dump(specs, f, indent=2)

    print("Filter design complete.")
    print(f"  Header  -> {HEADER_PATH}")
    print(f"  Specs   -> {SPECS_PATH}")
    print(f"  60 Hz notch attenuation : {specs['notch60_atten_db']:.1f} dB")
    print(f"  50 Hz notch attenuation : {specs['notch50_atten_db']:.1f} dB")
    print(f"  FIR group delay         : {specs['fir_group_delay_ms']:.1f} ms")
    print(f"  FIR symmetric (Q15)     : {specs['fir_symmetric']}")


if __name__ == "__main__":
    main()
