/*
 * filters.h - Q15 filter coefficients for STM32 CMSIS-DSP.
 * Generated by dsp/filter_design.py -- DO NOT EDIT MANUALLY.
 *
 * fs = 500.0 Hz, FIR taps = 128, IIR postshift = 1
 * 60 Hz notch attenuation : 239.9 dB
 * 50 Hz notch attenuation : 239.9 dB
 * FIR group delay         : 127.0 ms
 */

#ifndef FILTERS_H
#define FILTERS_H

#include "arm_math.h"

#define FILTER_FS_HZ          500
#define FIR_NUM_TAPS          128
#define IIR_NUM_STAGES        2
#define IIR_POST_SHIFT        1

/* 60 Hz notch -- CMSIS DF1 Q15 [b0, b1, b2, -a1, -a2] x stages */
static const q15_t notch_60hz_coeffs_q15[] = {
     16145, -23538,  16145,  23529, -15896,
     16145, -23538,  16145,  23529, -15896,
};

/* 50 Hz notch -- CMSIS DF1 Q15 [b0, b1, b2, -a1, -a2] x stages */
static const q15_t notch_50hz_coeffs_q15[] = {
     16148, -26128,  16148,  26112, -15896,
     16148, -26128,  16148,  26112, -15896,
};

/* Bandpass FIR 0.5-40 Hz, 128-tap, symmetric, Q15 */
static const q15_t fir_bp_coeffs_q15[128] = {
        -9,     -9,     -9,    -10,    -12,    -14,    -15,    -15,
       -15,    -15,    -16,    -17,    -20,    -22,    -24,    -25,
       -25,    -27,    -30,    -36,    -44,    -50,    -53,    -49,
       -42,    -33,    -29,    -34,    -49,    -70,    -90,   -100,
       -96,    -82,    -66,    -57,    -60,    -73,    -86,    -88,
       -77,    -58,    -51,    -74,   -136,   -221,   -290,   -294,
      -198,     -9,    213,    368,    347,     91,   -372,   -904,
     -1279,  -1255,   -656,    545,   2191,   3961,   5457,   6313,
      6313,   5457,   3961,   2191,    545,   -656,  -1255,  -1279,
      -904,   -372,     91,    347,    368,    213,     -9,   -198,
      -294,   -290,   -221,   -136,    -74,    -51,    -58,    -77,
       -88,    -86,    -73,    -60,    -57,    -66,    -82,    -96,
      -100,    -90,    -70,    -49,    -34,    -29,    -33,    -42,
       -49,    -53,    -50,    -44,    -36,    -30,    -27,    -25,
       -25,    -24,    -22,    -20,    -17,    -16,    -15,    -15,
       -15,    -15,    -14,    -12,    -10,     -9,     -9,     -9,
};

#endif /* FILTERS_H */
